-- SUDHA CRM - LIVE SERVER UPDATE SCRIPT
-- RUN THIS ON YOUR LIVE DATABASE TO SYNC THE SCHEMA

-- 1. Update partners table
ALTER TABLE partners ADD COLUMN IF NOT EXISTS business_type VARCHAR(100) DEFAULT NULL AFTER type;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT NULL AFTER address;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS state VARCHAR(100) DEFAULT NULL AFTER city;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS district VARCHAR(100) DEFAULT NULL AFTER state;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS pincode VARCHAR(10) DEFAULT NULL AFTER district;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS additional_gst TEXT DEFAULT NULL AFTER gstin;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS billing_address TEXT DEFAULT NULL AFTER address;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS payment_terms VARCHAR(255) DEFAULT NULL;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS status ENUM('active', 'inactive') DEFAULT 'active';

-- 2. Update sites table
ALTER TABLE sites ADD COLUMN IF NOT EXISTS state VARCHAR(100) DEFAULT NULL AFTER city;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS area VARCHAR(100) DEFAULT NULL AFTER city;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS district VARCHAR(100) DEFAULT NULL AFTER area;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS genre VARCHAR(100) DEFAULT NULL AFTER type;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS facing VARCHAR(50) DEFAULT NULL AFTER height;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS light_type ENUM('BL','NL','FL') DEFAULT 'NL' AFTER facing;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS grade ENUM('A','B','C') DEFAULT 'B' AFTER light_type;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS available_from DATE DEFAULT NULL AFTER status;

-- 3. Update proposals table
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS campaign_name VARCHAR(255) DEFAULT NULL AFTER proposal_number;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS contact_person VARCHAR(255) DEFAULT NULL AFTER client_id;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS total_days INT(11) DEFAULT NULL AFTER end_date;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS remark TEXT DEFAULT NULL AFTER total_days;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS discounting_pct DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS pricing_pct DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS printing_cost DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS mounting_cost DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS ha_markup_amount DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS ta_markup_amount DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS total_sqft FLOAT DEFAULT 0;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS price_per_sqft DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS display_cost DECIMAL(15,2) DEFAULT 0.00;

-- 4. Update purchase_orders & bookings table
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS total_amount DECIMAL(15,2) DEFAULT 0.00 AFTER igst_amount;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS printing_cost DECIMAL(15,2) DEFAULT 0.00 AFTER grand_total;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS mounting_cost DECIMAL(15,2) DEFAULT 0.00 AFTER printing_cost;

-- 5. Create missing tables if they don't exist
CREATE TABLE IF NOT EXISTS activity_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    action VARCHAR(255) NOT NULL,
    entity_type VARCHAR(50) DEFAULT NULL,
    entity_id INT DEFAULT NULL,
    description TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS campaigns (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_id VARCHAR(50) DEFAULT NULL,
    booking_id INT DEFAULT NULL,
    client_id INT NOT NULL,
    employee_id INT DEFAULT NULL,
    display_name VARCHAR(255) DEFAULT NULL,
    from_date DATE DEFAULT NULL,
    to_date DATE DEFAULT NULL,
    days INT DEFAULT NULL,
    sqft FLOAT DEFAULT NULL,
    amount DECIMAL(15,2) DEFAULT NULL,
    qos_pct DECIMAL(5,2) DEFAULT NULL,
    status ENUM('planned','approved','running','completed') DEFAULT 'planned',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    site_id INT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    is_primary TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
